name: Publish OmniTest to PyPI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install project
        run: |
          pip install -e ".[dev]"

      - name: Show Versions
        run: |
          python --version
          pip --version
          pylint --version
          pip freeze

      - name: Check formatting (Black)
        run: |
          black --check .

      # - name: Lint (Ruff)
      #   run: |
      #     ruff check .

      - name: Lint (Pylint)
        run: |
          pylint $(git ls-files '*.py')

      - name: Run Tests
        run: |
          pytest

      - name: Build Package
        run: |
          python -m build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/

  publish:
    name: Publish to PyPI
    needs: test

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/omnitest

    permissions:
      id-token: write

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1